import type { CareerPath, RiskTolerance } from '@/types'

export interface EventDefinition {
  id: string
  label: string
  category: 'positive' | 'negative' | 'neutral'
  baseRate: number // probability per tick (0–1)
  // Stage indices where this event can fire (0-5)
  stages: number[]
  // Career paths that allow this event (undefined = all)
  careers?: CareerPath[]
  // Stat thresholds required
  requires?: Partial<Record<string, number>>
  // Wealth delta range [min, max] in USD (can be negative)
  wealthDelta?: [number, number]
  // Score deltas
  happinessDelta?: [number, number]
  healthDelta?: [number, number]
  careerLevelDelta?: [number, number]
  relationshipDelta?: [number, number]
  // Multiplier on wealth (e.g., 1.5 = +50%, 0.5 = -50%)
  wealthMultiplier?: [number, number]
}

export const EVENT_CATALOG: EventDefinition[] = [
  // ─── POSITIVE ───────────────────────────────────────────
  {
    id: 'career_breakthrough',
    label: 'Career Breakthrough',
    category: 'positive',
    baseRate: 0.03,
    stages: [0, 1, 2, 3],
    careerLevelDelta: [1, 2],
    wealthDelta: [5000, 30000],
    happinessDelta: [10, 20],
  },
  {
    id: 'windfall_inheritance',
    label: 'Unexpected Inheritance',
    category: 'positive',
    baseRate: 0.008,
    stages: [1, 2, 3],
    wealthDelta: [50000, 500000],
    happinessDelta: [5, 15],
  },
  {
    id: 'wise_investment',
    label: 'Smart Investment Pays Off',
    category: 'positive',
    baseRate: 0.025,
    stages: [1, 2, 3, 4],
    wealthMultiplier: [1.15, 1.6],
    happinessDelta: [5, 15],
  },
  {
    id: 'startup_exit',
    label: 'Startup Exit',
    category: 'positive',
    baseRate: 0.015,
    stages: [1, 2, 3],
    careers: ['entrepreneurship', 'tech'],
    wealthDelta: [200000, 5000000],
    happinessDelta: [20, 40],
    careerLevelDelta: [1, 3],
  },
  {
    id: 'mentor_found',
    label: 'Influential Mentor Found',
    category: 'positive',
    baseRate: 0.02,
    stages: [0, 1],
    careerLevelDelta: [1, 2],
    happinessDelta: [10, 20],
  },
  {
    id: 'health_transformation',
    label: 'Health Transformation',
    category: 'positive',
    baseRate: 0.018,
    stages: [0, 1, 2, 3],
    healthDelta: [15, 30],
    happinessDelta: [10, 20],
  },
  {
    id: 'perfect_partnership',
    label: 'Perfect Business Partnership',
    category: 'positive',
    baseRate: 0.015,
    stages: [1, 2],
    wealthDelta: [20000, 100000],
    relationshipDelta: [10, 25],
    careerLevelDelta: [0, 1],
  },
  {
    id: 'viral_success',
    label: 'Work Goes Viral',
    category: 'positive',
    baseRate: 0.01,
    stages: [1, 2],
    careers: ['arts', 'tech', 'academia'],
    wealthDelta: [10000, 200000],
    happinessDelta: [15, 30],
    careerLevelDelta: [1, 3],
  },
  {
    id: 'dream_job',
    label: 'Dream Job Offer',
    category: 'positive',
    baseRate: 0.02,
    stages: [0, 1, 2],
    wealthDelta: [15000, 50000],
    happinessDelta: [20, 35],
    careerLevelDelta: [1, 2],
  },
  {
    id: 'real_estate_win',
    label: 'Real Estate Win',
    category: 'positive',
    baseRate: 0.02,
    stages: [2, 3, 4],
    wealthDelta: [30000, 250000],
    happinessDelta: [5, 15],
  },
  {
    id: 'award_recognition',
    label: 'Industry Award / Recognition',
    category: 'positive',
    baseRate: 0.015,
    stages: [1, 2, 3],
    happinessDelta: [15, 25],
    careerLevelDelta: [0, 1],
    wealthDelta: [5000, 20000],
  },
  {
    id: 'passive_income',
    label: 'Passive Income Stream',
    category: 'positive',
    baseRate: 0.018,
    stages: [2, 3, 4],
    wealthDelta: [10000, 80000],
    happinessDelta: [5, 15],
  },
  {
    id: 'medical_recovery',
    label: 'Full Health Recovery',
    category: 'positive',
    baseRate: 0.012,
    stages: [2, 3, 4, 5],
    healthDelta: [10, 25],
    happinessDelta: [15, 25],
  },
  {
    id: 'network_windfall',
    label: 'Network Opportunity',
    category: 'positive',
    baseRate: 0.025,
    stages: [0, 1, 2],
    wealthDelta: [8000, 40000],
    careerLevelDelta: [0, 1],
    happinessDelta: [5, 15],
  },
  {
    id: 'stock_options',
    label: 'Stock Options Vest',
    category: 'positive',
    baseRate: 0.02,
    stages: [1, 2, 3],
    careers: ['tech', 'finance'],
    wealthDelta: [20000, 500000],
    happinessDelta: [10, 20],
  },

  // ─── NEGATIVE ───────────────────────────────────────────
  {
    id: 'medical_emergency',
    label: 'Medical Emergency',
    category: 'negative',
    baseRate: 0.025,
    stages: [1, 2, 3, 4, 5],
    wealthDelta: [-200000, -30000],
    healthDelta: [-25, -10],
    happinessDelta: [-25, -10],
  },
  {
    id: 'divorce',
    label: 'Divorce',
    category: 'negative',
    baseRate: 0.015,
    stages: [1, 2, 3],
    wealthMultiplier: [0.60, 0.80],
    happinessDelta: [-35, -18],
    relationshipDelta: [-50, -30],
  },
  {
    id: 'layoff',
    label: 'Layoff / Job Loss',
    category: 'negative',
    baseRate: 0.03,
    stages: [0, 1, 2, 3],
    wealthDelta: [-30000, -5000],
    happinessDelta: [-30, -15],
    careerLevelDelta: [-1, 0],
  },
  {
    id: 'market_crash',
    label: 'Market Crash',
    category: 'negative',
    baseRate: 0.010,
    stages: [1, 2, 3, 4],
    careers: ['finance', 'entrepreneurship'],
    wealthMultiplier: [0.55, 0.78],
    happinessDelta: [-18, -8],
  },
  {
    id: 'burnout',
    label: 'Burnout',
    category: 'negative',
    baseRate: 0.025,
    stages: [1, 2, 3],
    happinessDelta: [-30, -15],
    healthDelta: [-15, -5],
    careerLevelDelta: [-1, 0],
    wealthDelta: [-10000, -2000],
  },
  {
    id: 'addiction_spiral',
    label: 'Addiction Spiral',
    category: 'negative',
    baseRate: 0.008,
    stages: [0, 1, 2, 3],
    happinessDelta: [-45, -25],
    healthDelta: [-30, -15],
    wealthDelta: [-50000, -10000],
    careerLevelDelta: [-2, -1],
  },
  {
    id: 'legal_trouble',
    label: 'Legal Trouble',
    category: 'negative',
    baseRate: 0.012,
    stages: [0, 1, 2, 3],
    wealthDelta: [-100000, -20000],
    happinessDelta: [-30, -15],
    careerLevelDelta: [-1, 0],
  },
  {
    id: 'bad_investment',
    label: 'Bad Investment',
    category: 'negative',
    baseRate: 0.025,
    stages: [1, 2, 3, 4],
    wealthDelta: [-80000, -10000],
    happinessDelta: [-15, -5],
  },
  {
    id: 'chronic_illness',
    label: 'Chronic Illness',
    category: 'negative',
    baseRate: 0.015,
    stages: [2, 3, 4, 5],
    healthDelta: [-25, -10],
    happinessDelta: [-20, -10],
    wealthDelta: [-40000, -5000],
  },
  {
    id: 'failed_business',
    label: 'Business Failure',
    category: 'negative',
    baseRate: 0.02,
    stages: [1, 2, 3],
    careers: ['entrepreneurship'],
    wealthDelta: [-200000, -30000],
    happinessDelta: [-35, -20],
    careerLevelDelta: [-2, -1],
  },
  {
    id: 'scam_victim',
    label: 'Fraud / Scam Victim',
    category: 'negative',
    baseRate: 0.01,
    stages: [0, 1, 2, 3, 4],
    wealthDelta: [-60000, -5000],
    happinessDelta: [-20, -10],
  },
  {
    id: 'natural_disaster',
    label: 'Natural Disaster',
    category: 'negative',
    baseRate: 0.008,
    stages: [1, 2, 3, 4],
    wealthDelta: [-80000, -15000],
    happinessDelta: [-20, -10],
    healthDelta: [-10, -3],
  },
  {
    id: 'depression_episode',
    label: 'Depression Episode',
    category: 'negative',
    baseRate: 0.02,
    stages: [0, 1, 2, 3, 4],
    happinessDelta: [-40, -20],
    healthDelta: [-10, -3],
    careerLevelDelta: [-1, 0],
  },
  {
    id: 'midlife_crisis',
    label: 'Midlife Crisis',
    category: 'negative',
    baseRate: 0.02,
    stages: [2],
    happinessDelta: [-30, -10],
    wealthDelta: [-30000, -5000],
  },

  // ─── NEUTRAL / LIFE ─────────────────────────────────────
  {
    id: 'marriage',
    label: 'Marriage',
    category: 'neutral',
    baseRate: 0.025,
    stages: [0, 1],
    happinessDelta: [10, 30],
    wealthDelta: [10000, 30000],
    relationshipDelta: [20, 40],
  },
  {
    id: 'child_born',
    label: 'Child Born',
    category: 'neutral',
    baseRate: 0.02,
    stages: [0, 1, 2],
    happinessDelta: [15, 35],
    wealthDelta: [-20000, -8000],
    healthDelta: [-3, 3],
  },
  {
    id: 'relocation',
    label: 'Major Relocation',
    category: 'neutral',
    baseRate: 0.018,
    stages: [0, 1, 2],
    wealthDelta: [-15000, 5000],
    happinessDelta: [-5, 20],
    careerLevelDelta: [0, 1],
  },
  {
    id: 'career_pivot',
    label: 'Career Pivot',
    category: 'neutral',
    baseRate: 0.015,
    stages: [1, 2],
    careerLevelDelta: [-3, -1],
    happinessDelta: [-10, 25],
    wealthDelta: [-10000, 5000],
  },
  {
    id: 'loss_of_parent',
    label: 'Loss of Parent',
    category: 'neutral',
    baseRate: 0.025,
    stages: [2, 3, 4],
    happinessDelta: [-30, -15],
    wealthDelta: [0, 100000],
  },
  {
    id: 'travel_growth',
    label: 'Life-Changing Travel',
    category: 'neutral',
    baseRate: 0.015,
    stages: [0, 1, 2],
    happinessDelta: [10, 25],
    wealthDelta: [-8000, -2000],
    healthDelta: [3, 8],
  },
  {
    id: 'spiritual_awakening',
    label: 'Spiritual / Philosophical Shift',
    category: 'neutral',
    baseRate: 0.012,
    stages: [1, 2, 3, 4],
    happinessDelta: [15, 30],
    careerLevelDelta: [-1, 0],
  },
  {
    id: 'retirement_early',
    label: 'Early Retirement',
    category: 'neutral',
    baseRate: 0.01,
    stages: [3],
    happinessDelta: [10, 30],
    careerLevelDelta: [0, 0],
  },
]
